### ISSUE TITLE
after setting up everything and setting up the enviroment i am getting this error

### ISSUE THREAD

**Issue by travelandcodes** [jayeshs999/ChatOn-Chat-App-in-Angular#1]
![Screenshot 2020-04-19 at 10 07 09 PM](https://user-images.githubusercontent.com/63969917/79693760-400e5400-828a-11ea-9901-4c6a4313cc0c.png)

**Comment by jayeshs999** [comment]
You also need to change 'read' and 'write' permissions to true for your Firebase database.

Go to the rules section and change them to true.
![Screenshot_20200420-142645](https://user-images.githubusercontent.com/55800453/79733606-033a6f80-8313-11ea-84d0-632b77037de4.jpg)

**Comment by travelandcodes** [comment]
thanks its working perfectly
